#ifndef CONFIG_RANGE_H
#define CONFIG_RANGE_H

#if !CONFIG_IGNORE_RANGE
#if (CONFIG_PASSWORD_LEN < 1) || (CONFIG_PASSWORD_LEN > 16)
#error "CONFIG_PASSWORD_LEN out of range"
#endif
#if (CONFIG_LCD_COLS < 8) || (CONFIG_LCD_COLS > 16)
#error "CONFIG_LCD_COLS out of range"
#endif
#if (CONFIG_PASSWORD_COL > (CONFIG_LCD_COLS - CONFIG_PASSWORD_LEN))
#error "CONFIG_PASSWORD_COL out of range"
#endif
#if (CONFIG_COUNTDOWN_MS < 1000)
#error "CONFIG_COUNTDOWN_MS out of range"
#endif
#if (CONFIG_ARM_DELAY_MS > 5000)
#error "CONFIG_ARM_DELAY_MS out of range"
#endif
#if (CONFIG_LCD_BACKLIGHT_PCT > 100)
#error "CONFIG_LCD_BACKLIGHT_PCT out of range"
#endif
#if (CONFIG_BEEP_LEN_MS < 10) || (CONFIG_BEEP_LEN_MS > 500)
#error "CONFIG_BEEP_LEN_MS out of range"
#endif
#if (CONFIG_BEEP_INTERVAL_BASE_MS < 10) || (CONFIG_BEEP_INTERVAL_BASE_MS > 1000)
#error "CONFIG_BEEP_INTERVAL_BASE_MS out of range"
#endif
#if (CONFIG_BEEP_INTERVAL_SCALE_MS > 2000)
#error "CONFIG_BEEP_INTERVAL_SCALE_MS out of range"
#endif
#if (CONFIG_BEEP_INTERVAL_MIN_MS < 50) || (CONFIG_BEEP_INTERVAL_MIN_MS > 1000)
#error "CONFIG_BEEP_INTERVAL_MIN_MS out of range"
#endif
#if (CONFIG_BEEP_INITIAL_MS > 5000)
#error "CONFIG_BEEP_INITIAL_MS out of range"
#endif
#if (CONFIG_LED_PWM_MAX < 100) || (CONFIG_LED_PWM_MAX > 10000)
#error "CONFIG_LED_PWM_MAX out of range"
#endif
#if (CONFIG_LED_BREATH_PERIOD_MS < 100) || (CONFIG_LED_BREATH_PERIOD_MS > 5000)
#error "CONFIG_LED_BREATH_PERIOD_MS out of range"
#endif
#if (CONFIG_LED_YELLOW_RED_PCT > 100)
#error "CONFIG_LED_YELLOW_RED_PCT out of range"
#endif
#if (CONFIG_SCROLL_INTERVAL_MS < 10) || (CONFIG_SCROLL_INTERVAL_MS > 500)
#error "CONFIG_SCROLL_INTERVAL_MS out of range"
#endif
#if (CONFIG_SCROLL_PATTERN_LEN < 1) || (CONFIG_SCROLL_PATTERN_LEN > 16)
#error "CONFIG_SCROLL_PATTERN_LEN out of range"
#endif
#if (CONFIG_LONG_PRESS_MS < 200) || (CONFIG_LONG_PRESS_MS > 3000)
#error "CONFIG_LONG_PRESS_MS out of range"
#endif
#if (CONFIG_MANUAL_DEFUSE_MS < 1000)
#error "CONFIG_MANUAL_DEFUSE_MS out of range"
#endif
#if (CONFIG_EXTERNAL_DEFUSE_MS < 1000)
#error "CONFIG_EXTERNAL_DEFUSE_MS out of range"
#endif
#if (CONFIG_DEFUSE_DISPLAY_HOLD_MS < 200) || (CONFIG_DEFUSE_DISPLAY_HOLD_MS > 5000)
#error "CONFIG_DEFUSE_DISPLAY_HOLD_MS out of range"
#endif
#if (CONFIG_DEFUSE_CYCLE_STEPS < 1) || (CONFIG_DEFUSE_CYCLE_STEPS > 20)
#error "CONFIG_DEFUSE_CYCLE_STEPS out of range"
#endif
#if (CONFIG_DEFUSE_FLASH_TOGGLE_MS < 10) || (CONFIG_DEFUSE_FLASH_TOGGLE_MS > 200)
#error "CONFIG_DEFUSE_FLASH_TOGGLE_MS out of range"
#endif
#if (CONFIG_DEFUSE_FLASH_TOGGLES < 1) || (CONFIG_DEFUSE_FLASH_TOGGLES > 20)
#error "CONFIG_DEFUSE_FLASH_TOGGLES out of range"
#endif
#if (CONFIG_DEFUSE_BLINK_MS < 100) || (CONFIG_DEFUSE_BLINK_MS > 1000)
#error "CONFIG_DEFUSE_BLINK_MS out of range"
#endif
#if (CONFIG_BUZZER_STARTUP_FREQ_HZ < 100) || (CONFIG_BUZZER_STARTUP_FREQ_HZ > 10000)
#error "CONFIG_BUZZER_STARTUP_FREQ_HZ out of range"
#endif
#if (CONFIG_BUZZER_COUNTDOWN_FREQ_HZ < 100) || (CONFIG_BUZZER_COUNTDOWN_FREQ_HZ > 10000)
#error "CONFIG_BUZZER_COUNTDOWN_FREQ_HZ out of range"
#endif
#if (CONFIG_BUZZER_DUTY_PCT > 50)
#error "CONFIG_BUZZER_DUTY_PCT out of range"
#endif
#if (CONFIG_STARTUP_BEEP_ON_MS < 10) || (CONFIG_STARTUP_BEEP_ON_MS > 500)
#error "CONFIG_STARTUP_BEEP_ON_MS out of range"
#endif
#if (CONFIG_STARTUP_BEEP_GAP_MS < 10) || (CONFIG_STARTUP_BEEP_GAP_MS > 500)
#error "CONFIG_STARTUP_BEEP_GAP_MS out of range"
#endif
#if (CONFIG_MP3_VOLUME > 30)
#error "CONFIG_MP3_VOLUME out of range"
#endif
#if (CONFIG_MP3_ARM_SUCCESS_ENABLE > 1)
#error "CONFIG_MP3_ARM_SUCCESS_ENABLE out of range"
#endif
#if (CONFIG_MP3_EXPLOSION_ENABLE > 1)
#error "CONFIG_MP3_EXPLOSION_ENABLE out of range"
#endif
#if (CONFIG_MP3_EXPLOSION_USE_MUSIC > 1)
#error "CONFIG_MP3_EXPLOSION_USE_MUSIC out of range"
#endif
#endif

#endif
